const LetterGifs = {
  a: require("../assets/gifs/a.gif"),
  b: require("../assets/gifs/b.gif"),
  c: require("../assets/gifs/c.gif"),
  d: require("../assets/gifs/c.gif"),
  e: require("../assets/gifs/e.gif"),
  f: require("../assets/gifs/f.gif"),
  g: require("../assets/gifs/g.gif"),
  h: require("../assets/gifs/h.gif"),
  i: require("../assets/gifs/i.gif"),
  j: require("../assets/gifs/j.gif"),
  k: require("../assets/gifs/k.gif"),
  l: require("../assets/gifs/l.gif"),
  m: require("../assets/gifs/m.gif"),
  n: require("../assets/gifs/n.gif"),
  o: require("../assets/gifs/o.gif"),
  p: require("../assets/gifs/p.gif"),
  q: require("../assets/gifs/q.gif"),
  r: require("../assets/gifs/r.gif"),
  s: require("../assets/gifs/s.gif"),
  t: require("../assets/gifs/t.gif"),
  u: require("../assets/gifs/u.gif"),
  v: require("../assets/gifs/v.gif"),
  w: require("../assets/gifs/w.gif"),
  x: require("../assets/gifs/x.gif"),
  y: require("../assets/gifs/y.gif"),
  z: require("../assets/gifs/z.gif")
};
export default LetterGifs;
