const WordImages = {
  a: require("../assets/word_pictures/a.png"),
  apple: require("../assets/word_pictures/apple.png"),
  ball: require("../assets/word_pictures/ball.png"),
  cat: require("../assets/word_pictures/cat.png"),
  dog: require("../assets/word_pictures/dog.png"),
  draw: require("../assets/word_pictures/draw.png"),
  drink: require("../assets/word_pictures/drink.png"),
  eat: require("../assets/word_pictures/eat.png"),
  egg: require("../assets/word_pictures/egg.png"),
  elephant: require("../assets/word_pictures/elephant.png"),
  fish: require("../assets/word_pictures/fish.png"),
  fly: require("../assets/word_pictures/fly.png"),
  hand: require("../assets/word_pictures/hand.png"),
  man: require("../assets/word_pictures/man.png"),
  play: require("../assets/word_pictures/play.png"),
  rain: require("../assets/word_pictures/rain.png"),
  read: require("../assets/word_pictures/read.png"),
  ride: require("../assets/word_pictures/ride.png"),
  run: require("../assets/word_pictures/run.png"),
  sheep: require("../assets/word_pictures/sheep.png"),
  sing: require("../assets/word_pictures/sing.png"),
  sleep: require("../assets/word_pictures/sleep.png"),
  sun: require("../assets/word_pictures/sun.png"),
  walk: require("../assets/word_pictures/walk.png"),
  water: require("../assets/word_pictures/water.png"),
  well: require("../assets/word_pictures/well.png")
};
export default WordImages;
